export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const COMPLETED_TODO = 'COMPLETED_TODO';
export const PROGRESS_TODO = 'PROGRESS_TODO';
export const FILTER_COMPLETED = 'FILTER_COMPLETED';
export const FILTER_INPROGRESS = 'FILTER_INPROGRESS';
export const FILTER_ALL = 'FILTER_ALL';


